Convert from Groovy to Java BaseWireMockStubStrategy.java
spring-cloud/spring-cloud-contract pull request #1479
Opened 2020-08-23 20:33 UTC by santfirax

converted files:
-BaseWireMockStubStrategy to BaseWireMockStubStrategy.java

related to #1470

2020-08-24 11:26 UTC, marcingrzejszczak requested changes

2020-08-24 11:26 UTC, marcingrzejszczak commented on spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/dsl/wiremock/BaseWireMockStubStrategy.java
> +		return MapConverter.transformValues(transformedMap, new Closure<Object>(this, this) {
Can we convert this to a Function?

2020-08-24 11:26 UTC, marcingrzejszczak commented on spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/dsl/wiremock/BaseWireMockStubStrategy.java
> +					if (!StringGroovyMethods.asBoolean(jsonPath)) {
We can use Java code with this one

2020-08-24 11:26 UTC, marcingrzejszczak commented on spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/dsl/wiremock/BaseWireMockStubStrategy.java
> +import groovy.lang.Reference;
It would be great not to reference any Groovy here (apart from GString I guess)

2020-08-24 11:26 UTC, marcingrzejszczak commented on spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/dsl/wiremock/BaseWireMockStubStrategy.java
> +		final Reference<List> result = new Reference<List>(new ArrayList());
Let's convert all of this to Java

2020-08-24 11:26 UTC, marcingrzejszczak commented on spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/dsl/wiremock/BaseWireMockStubStrategy.java
> +		Object processedValue = ContentUtils.extractValue(value, contentType, new Closure<Object>(this, this) {
Let's change Closure to a Function

2020-08-24 11:26 UTC, marcingrzejszczak commented on spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/dsl/wiremock/BaseWireMockStubStrategy.java
> +			Map convertedMap = DefaultGroovyMethods
Let's remove the type casting here and use Java code. Same with Closures.

2020-08-24 11:26 UTC, marcingrzejszczak commented on spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/dsl/wiremock/BaseWireMockStubStrategy.java
> +	private static Closure transform = new Closure<Object>(null, null) {
Let's remove Closures and move the fields to the top of the class

2020-08-24 14:38 UTC, santfirax commented
Hi @marcingrzejszczak  thanks for the feedback, I'll make the changes.

2020-10-29 12:23 UTC, marcingrzejszczak commented
Closing for now, please feel free to reopen once you update the code

2020-10-29 12:23 UTC, closed without merging

2020-12-25 03:29 UTC, santfirax commented
Hello @marcingrzejszczak  I've started working on this again and I've updated my branch by pulling master from spring cloud contract and I even got a copy from spring-cloud-contract master branch and both have the same problem when downloading some dependencies.
![Screenshot from 2020-12-24 19-23-02](https://user-images.githubusercontent.com/14352585/103117250-65740e80-461e-11eb-9ec5-9dc6fa354f6a.png)

2021-01-05 09:42 UTC, marcingrzejszczak commented
It tries to fetch jars from central. Please turn on the `spring` profile in your IDE and try again.