ghcDocumentUpdate
spring-cloud/spring-cloud-contract pull request #1527
Opened 2020-10-01 20:01 UTC by ashwinikatur

2020-10-01 20:01 UTC, pivotal-issuemaster commented
@ashwinikatur Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-contract&pullRequestId=1527)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-cloud/spring-cloud-contract&pullRequestId=1527) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

2020-10-01 20:02 UTC, pivotal-issuemaster commented
@ashwinikatur Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-cloud/spring-cloud-contract&pullRequestId=1527)!

2020-10-01 20:14 UTC, OlgaMaciaszek requested changes
Thanks for contributing this PR @ashwinikatur. There are a few item to modify.

2020-10-01 20:14 UTC, OlgaMaciaszek commented on docs/src/main/asciidoc/maven-project.adoc
> +*`httpPort` : HTTP port for the WireMock server that serves stubs. Currently spring.cloud.contract.verifier.http.port property works only when serving stubs from the directory. Otherwise, when provid
Add ticks (``) around `spring.cloud.contract.verifier.http.port`

2020-10-01 20:14 UTC, OlgaMaciaszek commented on docs/src/main/asciidoc/maven-project.adoc
Remove empty line.

2020-10-01 20:14 UTC, OlgaMaciaszek commented on docs/src/main/asciidoc/maven-project.adoc
> +*`skip`: Set this to true to bypass the verifier execution
Add ticks (``) around `true`

2020-10-01 20:14 UTC, OlgaMaciaszek commented on docs/src/main/asciidoc/maven-project.adoc
> +*`skip`: Set this to true to bypass the verifier execution
Add full stop.

2020-10-01 20:16 UTC, OlgaMaciaszek commented
Fixes gh-341.

2020-10-01 20:58 UTC, marcingrzejszczak approved these changes
LGTM! Congrats on your first PR 😀 Let's now wait for @Buzzardo 's review and we're ready to merge!

2020-10-01 20:59 UTC, marcingrzejszczak commented
Ah @OlgaMaciaszek  found some issues! Apparently she's got better 👀 than I do 😬

2020-10-01 21:45 UTC, OlgaMaciaszek approved these changes

2020-10-17 07:04 UTC, merged

2020-10-17 07:04 UTC, marcingrzejszczak commented
Congratulations @ashwinikatur on your first contribution to Spring Cloud Contract :)

2020-10-19 14:17 UTC, Buzzardo commented on docs/src/main/asciidoc/maven-project.adoc
> +*`httpPort` : HTTP port for the WireMock server that serves stubs. Currently `spring.cloud.contract.verifier.http.port` property works only when serving stubs from the directory. Otherwise, when prov
Change the second sentence to "Otherwise, when providing stubs IDs, the ports have to be included in the ID string."

2020-10-19 14:17 UTC, Buzzardo commented on docs/src/main/asciidoc/maven-project.adoc
> +*`minPort` : Specifies the minimal port at which the stub should start.
Change "minimal" to "minimum"

2020-10-19 14:17 UTC, Buzzardo commented on docs/src/main/asciidoc/maven-project.adoc
> +*`maxPort` : Specifies the maximal port at which the stub should start.
Change "maximal" to "maximum"

2020-10-19 14:17 UTC, Buzzardo commented on docs/src/main/asciidoc/maven-project.adoc
> +*`waitForKeyPressed` : Specifies if the plugin should wait for the user to press the key after starting the stubs.
Change "the key" to "a key"