Adds support for unqualified namespaced XML content
spring-cloud/spring-cloud-contract pull request #1590
Opened 2020-12-30 17:29 UTC by bono007

Adds support for unqualified namespaced XML content and fixes how qualified namespace URIs values are retrieved.

Fixes gh-1571 gh-1517

-----

### Overview
The main theme behind this change is to access XPath expressions for nodes that are using an unqualified namespace. Please read the document updates first as that should clarify a bit more.

This is definitely a problem of edge-casing and one could probably come up w/ a twisted nested complicated XML document that we may not properly support. I added in a decent set of complicated XML content in the tests but I also don't want to over complicate the maintenance of our tests. We can add more later if need be but we are definitely in a better position, code coverage wise, with the new additions in this code proposal.

----

#### Concern / Improvement

I want to point the verbose nature of the required XPath expressions.

For the following XML:
```xml
<customer xmlns="http://demo.com/customer">
    <email>customer@test.com</email>
</customer>
```
The XPath expression to select the email address is
```
*/[local-name()='customer' and namespace-uri()='http://demo.com/customer']/*[local-name()='email']/text()
```
We may want to consider later supporting a more user-friendly form in the body matchers so that users could instead specify the matcher expression in the unqualfied mamner such as:
```
/customer/email/text()
```
and we would behind the scenes translate that into the proper fully-qualified XPath expression:
```
*/[local-name()='customer' and namespace-uri()='http://demo.com/customer']/*[local-name()='email']/text()
```

2021-01-04 16:16 UTC, Buzzardo requested changes

2021-01-04 16:16 UTC, Buzzardo commented on docs/src/main/asciidoc/_project-features-contract.adoc
> +Namespaced XML is supported. However, any XPath expresssions used to select namespaced content must be updated slightly.
Remove "slightly"

2021-01-04 16:16 UTC, Buzzardo commented on docs/src/main/asciidoc/_project-features-contract.adoc
> +For content that uses an unqualfied namespace the expression is more verbose. Consider the following XML document that
In the first sentence, add a comma after "namespace"

2021-01-04 16:16 UTC, Buzzardo commented on docs/src/main/asciidoc/_project-features-contract.adoc
> +The XPath expression to select the email address is `/ns1:customer/email/text()`. Beware as the unqualified expression
Add a comma after "beware"

2021-01-04 16:16 UTC, Buzzardo commented on docs/src/main/asciidoc/_project-features-contract.adoc
> +The XPath expression to select the email address is
Add a colon after "is"

2021-01-04 16:16 UTC, Buzzardo commented on docs/src/main/asciidoc/_project-features-contract.adoc
> +`/customer/email/text()` results in `""`.
Add parentheses around \`/customer/email/text()\`

2021-01-04 16:16 UTC, Buzzardo commented on docs/src/main/asciidoc/_project-features-contract.adoc
> +Beware as the unqualified expressions `/customer/email/text()` or `*/[local-name()='customer' and namespace-uri()='http://demo.com/customer']/email/text()`
Change to:

Beware, as the unqualified expressions (\`/customer/email/text()\` or \`*/[local-name()='customer' and namespace-uri()='http://demo.com/customer']/email/text()\`)

2021-01-04 16:16 UTC, Buzzardo commented on docs/src/main/asciidoc/_project-features-contract.adoc
> +==== XML Support for namespaces
Capitalize "namespaces"

2021-01-04 16:16 UTC, Buzzardo commented on docs/src/main/asciidoc/_project-features-contract.adoc
> +====== General namespaced node expression syntax
Capitalize each word

2021-01-04 16:16 UTC, Buzzardo commented on docs/src/main/asciidoc/_project-features-contract.adoc
> +NOTE: In some case the `namespace_uri` portion can be omitted but may lead to ambiguity.
Change to

NOTE: In some cases, you can omit the \`namespace_uri`\ portion, but doing so may lead to ambiguity.

2021-01-06 05:09 UTC, bono007 commented
Thanks for the review @Buzzardo . I believe I addressed all of the comments.

2021-01-06 15:06 UTC, Buzzardo approved these changes

2021-01-06 15:06 UTC, Buzzardo commented
Thank you. :)

2021-01-08 12:03 UTC, OlgaMaciaszek approved these changes
Other than a minor change in the docs, LGTM. Thanks for the fix @bono007.

2021-01-08 13:25 UTC, bono007 commented
@OlgaMaciaszek I updated the docs. I really ❤️ that AsciDoc has that built-in support for `INFO/WARNING`... Trying to do so in plain markdown is not fun.

2021-01-08 14:06 UTC, merged

2021-01-08 14:06 UTC, marcingrzejszczak commented
Thanks a lot @bono007 !